// app/components/PDFDocument.tsx
import { Document, Page, Text, View, StyleSheet, Font } from '@react-pdf/renderer';

Font.register({
  family: 'Helvetica',
  fonts: [
    { src: 'https://fonts.gstatic.com/s/helvetica/v1/Helvetica.ttf' }
  ]
});

const styles = StyleSheet.create({
  page: {
    padding: 40,
    backgroundColor: '#ffffff',
    fontFamily: 'Helvetica',
  },
  header: {
    backgroundColor: '#7c3aed',
    color: 'white',
    padding: 20,
    marginBottom: 20,
    borderRadius: 8,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    textAlign: 'center',
    color: 'white',
  },
  headerSub: {
    fontSize: 12,
    textAlign: 'center',
    color: '#e2e8f0',
    marginTop: 4,
  },
  section: {
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#1a1a2e',
    marginBottom: 6,
    borderBottom: '1px solid #e2e8f0',
    paddingBottom: 4,
  },
  bodyText: {
    fontSize: 10,
    color: '#334155',
    lineHeight: 1.6,
    marginBottom: 4,
  },
  listItem: {
    fontSize: 10,
    color: '#334155',
    marginLeft: 12,
    marginBottom: 2,
  },
  footer: {
    marginTop: 30,
    paddingTop: 10,
    borderTop: '1px solid #e2e8f0',
    textAlign: 'center',
  },
  footerText: {
    fontSize: 8,
    color: '#94a3b8',
  },
  disclaimer: {
    fontSize: 7,
    color: '#94a3b8',
    textAlign: 'center',
    marginTop: 6,
    fontStyle: 'italic',
  },
});

interface PDFDocumentProps {
  tool: string;
  type: string;
  formData: any;
  generatedContent: string;
}

export function PDFDocument({ tool, type, formData, generatedContent }: PDFDocumentProps) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.headerTitle}>✨ LEGAL GALAXY</Text>
          <Text style={styles.headerSub}>Privacy & AI Governance Universe</Text>
        </View>

        {/* Title */}
        <View style={styles.section}>
          <Text style={{ fontSize: 20, fontWeight: 'bold', color: '#1a1a2e', textAlign: 'center', marginBottom: 8 }}>
            {tool.replace('-', ' ').toUpperCase()}
          </Text>
          <Text style={{ fontSize: 10, color: '#64748b', textAlign: 'center' }}>
            Organisation: {formData.orgName || '[Organisation Name]'}
          </Text>
          <Text style={{ fontSize: 10, color: '#64748b', textAlign: 'center' }}>
            Effective Date: {new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}
          </Text>
        </View>

        {/* Content */}
        <View style={styles.section}>
          <Text style={styles.bodyText}>{generatedContent}</Text>
        </View>

        {/* Footer */}
        <View style={styles.footer}>
          <Text style={styles.footerText}>Generated by Legal Galaxy</Text>
          <Text style={styles.footerText}>© {new Date().getFullYear()} Legal Galaxy. All rights reserved.</Text>
          <Text style={styles.footerText}>Powered by BusinezExcellence StartX LLP</Text>
          <Text style={styles.disclaimer}>This document is for informational purposes and does not constitute legal advice.</Text>
        </View>
      </Page>
    </Document>
  );
}