// ===== NO "use client" =====
// This is a Server Component

import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: {
    padding: 50,
    backgroundColor: '#ffffff',
  },
  header: {
    backgroundColor: '#004d40',
    padding: 20,
    marginBottom: 20,
    borderRadius: 4,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    textAlign: 'center',
    color: '#ffffff',
  },
  headerSub: {
    fontSize: 11,
    textAlign: 'center',
    color: '#80cbc4',
    marginTop: 4,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#004d40',
    marginTop: 12,
    marginBottom: 4,
    borderBottom: '1px solid #e0e8e4',
    paddingBottom: 4,
  },
  bodyText: {
    fontSize: 10,
    color: '#334155',
    lineHeight: 1.6,
    marginBottom: 2,
  },
  footer: {
    marginTop: 30,
    paddingTop: 10,
    borderTop: '1px solid #e0e8e4',
    textAlign: 'center',
  },
  footerText: {
    fontSize: 8,
    color: '#8aaa9a',
  },
  disclaimer: {
    fontSize: 7,
    color: '#aac0b5',
    textAlign: 'center',
    marginTop: 6,
    fontStyle: 'italic',
  },
});

interface PDFDocumentProps {
  tool: string;
  type: string;
  formData: any;
  generatedContent: string;
}

export function PDFDocument({ tool, type, formData, generatedContent }: PDFDocumentProps) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.headerTitle}>✨ LEGAL GALAXY</Text>
          <Text style={styles.headerSub}>Privacy & AI Governance Universe</Text>
        </View>

        {/* Title */}
        <View style={{ marginBottom: 16 }}>
          <Text style={{ fontSize: 18, fontWeight: 'bold', color: '#004d40', textAlign: 'center', marginBottom: 6 }}>
            {tool.replace('-', ' ').toUpperCase()}
          </Text>
          <Text style={{ fontSize: 10, color: '#6a8a7a', textAlign: 'center' }}>
            Organisation: {formData.orgName || '[Organisation Name]'}
          </Text>
          <Text style={{ fontSize: 10, color: '#6a8a7a', textAlign: 'center' }}>
            Effective Date: {new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}
          </Text>
        </View>

        {/* Content */}
        <View>
          <Text style={styles.bodyText}>{generatedContent}</Text>
        </View>

        {/* Footer */}
        <View style={styles.footer}>
          <Text style={styles.footerText}>Generated by Legal Galaxy</Text>
          <Text style={styles.footerText}>© {new Date().getFullYear()} Legal Galaxy. All rights reserved.</Text>
          <Text style={styles.footerText}>Powered by BusinezExcellence StartX LLP</Text>
          <Text style={styles.disclaimer}>This document is for informational purposes and does not constitute legal advice.</Text>
        </View>
      </Page>
    </Document>
  );
}