// ===== NO "use client" =====
// This is a Server Component

import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: {
    padding: 50,
    backgroundColor: '#ffffff',
  },
  header: {
    backgroundColor: '#004d40',
    padding: 20,
    marginBottom: 20,
    borderRadius: 4,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    textAlign: 'center',
    color: '#ffffff',
    letterSpacing: 1,
  },
  headerSub: {
    fontSize: 10,
    textAlign: 'center',
    color: '#80cbc4',
    marginTop: 2,
  },
  documentTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#004d40',
    textAlign: 'center',
    marginBottom: 4,
  },
  documentMeta: {
    fontSize: 9,
    color: '#6a8a7a',
    textAlign: 'center',
    marginBottom: 16,
  },
  section: {
    marginBottom: 10,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#004d40',
    marginBottom: 4,
    borderBottom: '1px solid #e0e8e4',
    paddingBottom: 2,
  },
  bodyText: {
    fontSize: 9,
    color: '#334155',
    lineHeight: 1.6,
    marginBottom: 2,
  },
  listItem: {
    fontSize: 9,
    color: '#334155',
    marginLeft: 12,
    marginBottom: 1,
  },
  footer: {
    marginTop: 30,
    paddingTop: 10,
    borderTop: '1px solid #e0e8e4',
    textAlign: 'center',
  },
  footerText: {
    fontSize: 8,
    color: '#8aaa9a',
  },
  disclaimer: {
    fontSize: 7,
    color: '#aac0b5',
    textAlign: 'center',
    marginTop: 4,
    fontStyle: 'italic',
  },
  documentId: {
    fontSize: 7,
    color: '#8aaa9a',
    textAlign: 'center',
    marginTop: 4,
  },
});

interface PDFDocumentProps {
  tool: string;
  type: string;
  formData: any;
  generatedContent: string;
}

export function PDFDocument({ tool, type, formData, generatedContent }: PDFDocumentProps) {
  const docId = `BE-${tool.toUpperCase().slice(0, 4)}-${Date.now().toString().slice(-6)}`;

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header - BusinezExcellence Branding */}
        <View style={styles.header}>
          <Text style={styles.headerTitle}>BUSINEZEXCELLENCE STARTX LLP</Text>
          <Text style={styles.headerSub}>Legal Galaxy · Document Generator</Text>
        </View>

        {/* Document Title */}
        <Text style={styles.documentTitle}>
          {tool.replace('-', ' ').toUpperCase()}
        </Text>
        <Text style={styles.documentMeta}>
          Organisation: {formData.orgName || '[Organisation Name]'} | Effective: {new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}
        </Text>

        {/* Content */}
        <View>
          <Text style={styles.bodyText}>{generatedContent}</Text>
        </View>

        {/* Footer - Only One */}
        <View style={styles.footer}>
          <Text style={styles.footerText}>Generated by BusinezExcellence StartX LLP</Text>
          <Text style={styles.footerText}>© {new Date().getFullYear()} BusinezExcellence StartX LLP. All rights reserved.</Text>
          <Text style={styles.documentId}>Document ID: {docId}</Text>
          <Text style={styles.disclaimer}>This document is for informational purposes and does not constitute legal advice.</Text>
        </View>
      </Page>
    </Document>
  );
}