import { NextResponse } from 'next/server';
import { Resend } from 'resend';
import { PDFDocument } from '@/app/components/PDFDocument';
import { renderToStream } from '@react-pdf/renderer';
import { google } from 'googleapis';

const resend = new Resend(process.env.RESEND_API_KEY);

// ===== GOOGLE SHEETS AUTH =====
const auth = new google.auth.GoogleAuth({
  scopes: ['https://www.googleapis.com/auth/spreadsheets'],
});
const sheets = google.sheets({ version: 'v4', auth });

// ===== GENERATE TEMPLATE CONTENT =====
function generateTemplateContent(tool: string, formData: any): string {
  const templates: Record<string, string> = {
    'privacy-notice': `
1. INTRODUCTION
[Organisation Name] is committed to protecting your privacy.

2. DATA WE COLLECT
${(formData.dataTypes || ['Name', 'Email', 'Phone']).join(', ')}

3. PURPOSE OF PROCESSING
${(formData.purposes || ['Service Delivery', 'Communication']).join(', ')}

4. YOUR RIGHTS
Right to Access, Correction, Erasure, Portability, Withdraw Consent.

5. CONTACT
Data Protection Officer: ${formData.dpoName || '[DPO Name]'} - ${formData.dpoEmail || '[DPO Email]'}
    `,
    // Add other templates here
  };

  return templates[tool] || templates['privacy-notice'];
}

export async function POST(request: Request) {
  try {
    const { email, tool, type, name, phone, company, formData } = await request.json();

    if (!email) {
      return NextResponse.json(
        { success: false, message: 'Email is required' },
        { status: 400 }
      );
    }

    // ===== GENERATE CONTENT =====
    const content = generateTemplateContent(tool, formData);
    const fullContent = `
      ${content}
      ---
      Generated by Legal Galaxy
      © ${new Date().getFullYear()} Legal Galaxy
    `;

    // ===== GENERATE PDF =====
    const pdfStream = await renderToStream(
      PDFDocument({
        tool,
        type,
        formData,
        generatedContent: fullContent,
      })
    );

    // ===== SEND EMAIL WITH PDF ATTACHMENT =====
    const { data, error } = await resend.emails.send({
      from: 'Legal Galaxy <info@businezexcellence.com>',
      to: [email],
      subject: `📄 Your ${tool.replace('-', ' ')} Document`,
      html: `
        <!DOCTYPE html>
        <html>
        <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>Your Document is Ready</title>
        </head>
        <body style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; background: #f8fafc;">
          <div style="background: linear-gradient(to right, #7c3aed, #6d28d9); color: white; padding: 30px 20px; text-align: center; border-radius: 12px 12px 0 0;">
            <h1 style="margin: 0; font-size: 28px;">✨ Legal Galaxy</h1>
            <p style="margin: 5px 0 0; opacity: 0.8;">Privacy & AI Governance</p>
          </div>
          <div style="background: white; padding: 30px; border-radius: 0 0 12px 12px; box-shadow: 0 4px 6px rgba(0,0,0,0.05);">
            <h2 style="color: #1a1a2e; margin-top: 0;">📄 Your Document is Ready!</h2>
            <p style="color: #334155;">Thank you for using Legal Galaxy Document Generator.</p>
            <div style="background: #f1f5f9; padding: 16px; border-radius: 8px; margin: 20px 0;">
              <p style="margin: 4px 0;"><strong>Document:</strong> ${tool.replace('-', ' ')}</p>
              <p style="margin: 4px 0;"><strong>Category:</strong> ${type === 'privacy' ? 'Privacy' : 'AI Governance'}</p>
            </div>
            <p style="color: #334155;">Your PDF document is attached to this email.</p>
            <a href="${process.env.NEXT_PUBLIC_APP_URL}/generator" style="display: inline-block; background: #7c3aed; color: white; padding: 12px 30px; border-radius: 8px; text-decoration: none; font-weight: 600; margin-top: 10px;">Generate More</a>
          </div>
          <div style="text-align: center; padding: 20px; color: #64748b; font-size: 12px;">
            <p>© ${new Date().getFullYear()} Legal Galaxy. All rights reserved.</p>
            <p style="font-size: 10px;">Powered by BusinezExcellence StartX LLP</p>
          </div>
        </body>
        </html>
      `,
      attachments: [
        {
          filename: `${tool.replace('-', '_')}_${new Date().toISOString().slice(0, 10)}.pdf`,
          content: pdfStream,
        },
      ],
    });

    if (error) {
      console.error('Email error:', error);
      return NextResponse.json(
        { success: false, message: 'Email failed: ' + error.message },
        { status: 500 }
      );
    }

    // ===== STORE IN GOOGLE SHEETS =====
    try {
      await sheets.spreadsheets.values.append({
        spreadsheetId: process.env.GOOGLE_SHEET_ID,
        range: 'Sheet1!A:H',
        valueInputOption: 'USER_ENTERED',
        requestBody: {
          values: [[
            new Date().toISOString(),
            email,
            name || '',
            phone || '',
            company || '',
            tool || '',
            type || '',
            'PDF Sent'
          ]],
        },
      });
    } catch (sheetError) {
      console.error('Sheet error:', sheetError);
    }

    return NextResponse.json({
      success: true,
      message: 'Email sent with PDF attachment!',
    });
  } catch (error) {
    console.error('Error:', error);
    return NextResponse.json(
      { success: false, message: 'Server error' },
      { status: 500 }
    );
  }
}